name: cattle_health
description: "PashuSehat - Animal Health Monitoring Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Routing
  go_router: ^13.2.0

  # Data Visualization
  fl_chart: ^0.66.2

  # Code Generation & JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
